//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjudicacionLicitacionProveedor
    {
        public int IdAdjudicacion { get; set; }
        public int IdLicitacion { get; set; }
        public int IdCotizacion { get; set; }
        public int IdProducto { get; set; }
        public string FormaPagoAdj { get; set; }
    
        public virtual LicitacionCotizacionProv LicitacionCotizacionProv { get; set; }
        public virtual Licitacione Licitacione { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
