//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licitador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licitador()
        {
            this.Licitaciones = new HashSet<Licitacione>();
        }
    
        public int IdLicitador { get; set; }
        public int IdOrganismoLicitante { get; set; }
        public string NombreLicitador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licitacione> Licitaciones { get; set; }
        public virtual OrganismoLicitante OrganismoLicitante { get; set; }
    }
}
