//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicitacionCotizacionProv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LicitacionCotizacionProv()
        {
            this.AdjudicacionLicitacionProveedors = new HashSet<AdjudicacionLicitacionProveedor>();
        }
    
        public int IdCotizacion { get; set; }
        public int IdLicitacion { get; set; }
        public int IdProducto { get; set; }
        public int IdProveedor { get; set; }
        public System.DateTime FechaCotizacionProveedor { get; set; }
        public int PrecioUnitario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjudicacionLicitacionProveedor> AdjudicacionLicitacionProveedors { get; set; }
        public virtual Licitacione Licitacione { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
