//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalCompras.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalComprasEntities : DbContext
    {
        public PortalComprasEntities()
            : base("name=PortalComprasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjudicacionLicitacionProveedor> AdjudicacionLicitacionProveedors { get; set; }
        public virtual DbSet<LicitacionCotizacionProv> LicitacionCotizacionProvs { get; set; }
        public virtual DbSet<Licitacione> Licitaciones { get; set; }
        public virtual DbSet<Licitador> Licitadors { get; set; }
        public virtual DbSet<OrganismoLicitante> OrganismoLicitantes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
    }
}
